name: Ruby

on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Build
      run: |
        gem install bundler -N
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rake
      env:
        TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
